edition = "2021"
max_width = 100
use_small_heuristics = "Max"
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_field_init_shorthand = true
use_try_shorthand = true
reorder_modules = true
match_block_trailing_comma = true
